# Generated by Django 4.0.4 on 2022-05-01 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 4, 31, 26, 413444)),
        ),
    ]
