# Generated by Django 4.0.4 on 2022-05-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_docs_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
